### ISSUE TITLE
Detection Boxes are not split for multiple texts in scene

### ISSUE THREAD

**Issue by mohammedayub44** [bharatsubedi/OCR-Text-detection-and-Recognition-#5]
Hi,

Test.py script seems to produce always one bounding box with merged strings present in the scene like below. I want them to be separate for each text and also the bounding boxes are not rotated. Is there a simple way to achieve the separate boxes with text and rotation piece ?

**Examples:**
![building_60_35](https://user-images.githubusercontent.com/7122670/118752658-84737700-b831-11eb-8857-a597ee2997f5.jpg)

![crater_122_18](https://user-images.githubusercontent.com/7122670/118752675-8c331b80-b831-11eb-836e-37117f43e2fa.jpg)

Appreciate any guidance. Thanks !

**Comment by bharatsubedi** [comment]
@mohammedayub44 if you check test.py file clearly you can understand how the output will come from the network. In my case, I have to combine and merge all output strings into one so that I merged after detection and recognition completely. if you want all separate just remove the merge part and and use 
for i, box in enumerate(boxes):
                poly = np.array(box).astype(np.int32).reshape((-1))
                poly = poly.reshape(-1, 2)
                cv2.polylines(img, [poly.reshape((-1, 1, 2))], True, color=(0, 0, 255), thickness=1)

I trained network with character by characters, in your case you have to train your network word by word.

**Comment by mohammedayub44** [comment]
Sounds good. I'll try it out.
